version: '2'
services:
    web:
        build: .
        volumes:
            - ~/.google/credentials/:/.google/credentials:ro
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: /.google/credentials/google_credentials.json
        ports:
            - "80:80"
        restart: always

